### ISSUE TITLE
Problem with solution to exercise 1.3

### ISSUE THREAD

**Issue by kmaddox-ebsco** [zv/SICP-guile#10]
Your solution to exercise 1.3 has a problem.

Testing against the following inputs

    (largest-squares 1 2 3)
    (largest-squares 1 3 2)
    (largest-squares 2 3 1)
    (largest-squares 2 1 3)
    (largest-squares 3 2 1)
    (largest-squares 3 1 2)
    (largest-squares 3 1 3)
    (largest-squares 3 3 1)
    (largest-squares 1 3 3)

The expected output would be 
```
13
13
13
13
13
13
18
18
18
```
but the resulting output is 
```
13
18
18
13
13
13
18
18
18
```
I suggest changing to some variation of 
```
(define (square x) (* x x))

(define (sum-of-squares x y) (+ (square x) (square y)))

(sum-of-squares 3 4)

(define (>= x y)
  (not (< x y))) 

(define (largest-squares x y z)
  (sum-of-squares (if (>= x y)
                      (if (>= x z) x z)
                      (if (>= y z) y z))
                  (if (>= x y)
                      (if (>= x z)
                          (if (>= z y) z y)
                          x)
                      (if (>= y z)
                          (if (>= x z) x z)
                          y))))
```
This code gives the correct expected results

**Comment by zv** [comment]
You're absolutely right, I'll change that now.
