### ISSUE TITLE
Racket: Allow redefinition

### ISSUE THREAD

**Issue by soegaard** [zv/SICP-guile#3]
Hi,

In DrRacket it is easy to enable redefinitions in the repl.
In the menu "Language" choose the menu item "Choose Language...".
Click the button "Show Details". Remove the tick in "Enforce constant definitions".

After running the program it is now possible to use define in the repl.

/Jens Axel

**Comment by zv** [comment]
Thank you for this tip @soegaard 

I had no idea!

Unfortunately, the issue is primarily for function's and redefining still throws an error, even with the tick you described *or* `(compile-enforce-module-constants #f)`
